### ISSUE TITLE
Error while loading MNIST data - logistic regression tutorial 

### ISSUE THREAD

**Issue by rbhambriiit** [mGalarnyk/Python_Tutorials#1]
While following part2 of the tutorial:
https://medium.com/@GalarnykMichael/logistic-regression-using-python-sklearn-numpy-mnist-handwriting-recognition-matplotlib-a6b31e2b166a

For some reason, ‘loadmnist’ method did not work very well for me. 

I faced an error: 
errorTraceback (most recent call last)
<ipython-input-12-bd701362d5ed> in <module>()
      1 train_img, train_lbl = loadmnist('data/train-images-idx3-ubyte'
----> 2                                  , 'data/train-labels-idx1-ubyte')
      3 # test_img, test_lbl = loadmnist('data/t10k-images-idx3-ubyte'
      4   #                             , 'data/t10k-labels-idx1-ubyte')

<ipython-input-11-2121100c48fb> in loadmnist(imagefile, labelfile)
     25         for j in range(rows*cols):
     26             tmp_pixel = images.read(1)  # Just a single byte
---> 27             tmp_pixel = unpack('>B', tmp_pixel)[0]
     28             x[i][j] = tmp_pixel
     29         tmp_label = labels.read(1)

error: unpack requires a string argument of length 1

I did try to follow along the tutorial. 
I guess it has to do with the magic numbers used. 
Did not get much time to debug it though. Just letting you know.

**Comment by mGalarnyk** [comment]
Hey rbhambriiit, 

I think I should look for an alternative because chances are if you are having the issue, someone else is. 

I changed the method of loading the data in this notebook. 
https://github.com/mGalarnyk/Python_Tutorials/blob/master/Sklearn/Logistic_Regression/LogisticRegression_MNIST-Easier_Loading.ipynb

Can you look at it and see if it works better? I used 

```
# Used for Downloading MNIST
from sklearn.datasets import fetch_mldata

# Change data_home to wherever to where you want to download your data
mnist = fetch_mldata('MNIST original', data_home='~/Desktop/alternativeData')
```
