### ISSUE TITLE
fetch_mldata deprecated

### ISSUE THREAD

**Issue by hhuuggoo** [mGalarnyk/Python_Tutorials#10]
Hi Michael,  I was looking at your sklearn notebooks, but I ran into this: 
 
https://github.com/scikit-learn/scikit-learn/issues/8588

Have you already addressed this somewhere?

Thanks

**Comment by mGalarnyk** [comment]
Hey! 

I haven't addressed this yet. If you have a pull request, I would be happy to look it over.
