### ISSUE TITLE
Very beginner issue

### ISSUE THREAD

**Issue by cocoblabla** [mGalarnyk/Python_Tutorials#15]
Hi 
I 'm trying to use your code but it gave me this error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-7a39ca7aebeb> in <module>
      1 import pandas as pd
      2 import numpy as np
----> 3 import matplotlib.pyplot as plt
      4 from sklearn.decomposition import PCA
      5 from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'matplotlib'

Can you help me to solve it? 

Thank you

**Comment by csrdsg** [comment]
Hi!

Probably a simple `pip install matplotlib` gonna solve the problem, but you find the link here:
[https://matplotlib.org/users/installing.html](url)

If you not really used your machine for Python before maybe you need to refresh Python or pip or both. I hope its help.

**Comment by mGalarnyk** [comment]
Thanks @csrdsg for your help! It is correct.
