### ISSUE TITLE
PCA_to_Speed-up_Machine_Learning_Algorithms

### ISSUE THREAD

**Issue by c0gnitive3ngineer** [mGalarnyk/Python_Tutorials#17]
What other algorithms would you say are better than Logistic Regression? and how did you do the inverse transformation?

**Comment by csrdsg** [comment]
1. Part
Better? I'dont think thats a well articulated question here. Logistic Regression (as you can learn earlier) used to solve classification problems. So I you need a classification algorithm you can use linear models like: Logistic Regression, Support Vector Machines and non-linear models like: K-Nearest Neighbours, Decision Tree Classification and Random Forest Classification etc. They are not usually better or worse, you can compare them to find and ideal. 

2. Part
You mean like this...? 
```import numpy as np
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit(data)

data_reduced = np.dot(data, pca.components_.T) # transform
data_original = np.dot(data_reduced, pca.components_) # inverse_transform
