### ISSUE TITLE
not able to download Helix_parameters.csv file 

### ISSUE THREAD

**Issue by PriyankaGulhane** [mGalarnyk/Python_Tutorials#3]
help me

**Comment by mGalarnyk** [comment]
Put this link in your browser. 

https://github.com/mGalarnyk/Python_Tutorials/raw/master/Request/Data/helix_parameters.csv

**Comment by PriyankaGulhane** [comment]
In this link I can see the database on browser but i cant download that.

On Thu, Dec 14, 2017 at 11:12 PM, Michael Galarnyk <notifications@github.com

**Comment by mGalarnyk** [comment]
windows: control + s 
Mac: command + s

**Comment by PriyankaGulhane** [comment]
thank you


On Thu, Dec 14, 2017 at 11:23 PM, Michael Galarnyk <notifications@github.com

**Comment by mGalarnyk** [comment]
<img width="1152" alt="dontappend" src="https://user-images.githubusercontent.com/11932986/34006922-e5587f82-e0b4-11e7-9770-b6bf75846a10.png">

**Comment by mGalarnyk** [comment]
just press don't append if you get a message like this above.

**Comment by PriyankaGulhane** [comment]
Its done successfully.

Do you have any idea about how to install matplotlib for tensorflow
jyupetr  in windows 10.


On Thu, Dec 14, 2017 at 11:25 PM, Michael Galarnyk <notifications@github.com

**Comment by mGalarnyk** [comment]
https://medium.com/@GalarnykMichael/install-python-on-windows-anaconda-c63c7c3d1444
Install anaconda it comes with Matplotlib and Jupyter. 

Install tensor flow after using 
https://www.tensorflow.org/install/install_windows#installing_with_anaconda

**Comment by PriyankaGulhane** [comment]
I have already installed the Tensorflow with anaconda jupyter.

However whenever I m trying this
%pylab inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

getting errie



On Thu, Dec 14, 2017 at 11:42 PM, Michael Galarnyk <notifications@github.com
