### ISSUE TITLE
Hello getting error while performing the same code with my own dataset.

### ISSUE THREAD

**Issue by PriyankaGulhane** [mGalarnyk/Python_Tutorials#5]

**Comment by PriyankaGulhane** [comment]
# reset the locs in the blocks to correspond to our

DataError: No numeric types to aggregate

**Comment by mGalarnyk** [comment]
post entire notebook somewhere where I can see it as well as what code in particular you are trying to run.

**Comment by PriyankaGulhane** [comment]
Here I have attached the ipython and dataset files


On Wed, Mar 28, 2018 at 12:25 PM, Michael Galarnyk <notifications@github.com

**Comment by PriyankaGulhane** [comment]
Can You please help me, soon.

**Comment by mGalarnyk** [comment]
you never attached anything... Mind putting it on some GitHub repo or something?
