### ISSUE TITLE
Didn't Display

### ISSUE THREAD

**Issue by rizama** [mGalarnyk/Python_Tutorials#8]
If i Run With CMD / Terminal .. there is no happened . but if i running with Jupyter Notebook.. it will show the graph.. what should i do if i want show it grafic, via terminal or CMD.. thankssss

**Comment by mGalarnyk** [comment]
Which notebook are you talking about?  (share a link)I can show you how to fix for all, but specific fixes are easier.

**Comment by rizama** [comment]
@mGalarnyk , This book Python_Tutorials/Sklearn/PCA/PCA_Data_Visualization_Iris_Dataset_Blog.ipynb 
https://github.com/mGalarnyk/Python_Tutorials/blob/master/Sklearn/PCA/PCA_Data_Visualization_Iris_Dataset_Blog.ipynb

I tried running the code in the notebook jupyter, and it went well this is picture 
![image](https://user-images.githubusercontent.com/26889811/43972679-5c0b466c-9cff-11e8-936a-d14beab2e671.png)
But when i tried the code in CMD like "python test2.py" (i saved the code with name test2.py)  the graph doesn't come out.. like this : 
![image](https://user-images.githubusercontent.com/26889811/43972790-c5647c6e-9cff-11e8-84de-224b88e724eb.png)
please tell me how to bring up the graph when i running on CMD.. 

thanks before

**Comment by mGalarnyk** [comment]
try something simpler first 

name a file test.py and insert the following code. 
```
import matplotlib.pyplot as plt
plt.plot(range(10))
plt.show()
```
open a command prompt and type the following

python test.py

<img width="1188" alt="testinggraph" src="https://user-images.githubusercontent.com/11932986/43974548-c4895d0c-9c8f-11e8-9684-a9a2558d4e51.png">


Do this work for you? Often when I have issues, I start with simpler problems and then work on harder things after.

**Comment by rizama** [comment]
@mGalarnyk , thanks.. it solvedd show in command prompt
